### ISSUE TITLE
FM-index

### ISSUE THREAD

**Issue by lipanpanpanpanpan** [egonelbre/fm-index#1]
I want to know how shoud I do if I want to give file path to python file rather than use it in CMD?

**Comment by lipanpanpanpanpan** [comment]
Can you help me?

**Comment by egonelbre** [comment]
I know English is not the first language, but can you explain a little further what you are trying to achieve?

The command line tools are fairly limited, such enough to show it works:

```
$ ./fm-build.py data/test_data data/test_idx 
$ ./fm-search.py data/test_idx "acgt"
```

When you want to use it as a library you can look at the same files as an example how to use it:

1. https://github.com/egonelbre/fm-index/blob/master/src/fm-build.py
2. https://github.com/egonelbre/fm-index/blob/master/src/fm-search.py

Or in other words:

```
# creating the index
data = inp.read('data')
idx = fmindex.index(data)
fmindex.save('data.idx', idx)

# using the index later
idx = fmindex.load('data.idx)
result = idx.search('acgt')
```

_Also be patient, people have other things to do and cannot always immediately respond and responding takes time. Sometimes it takes few minutes, sometimes a week._

**Comment by egonelbre** [comment]
Although, I should remind you that this is a reference implementation for learning, not a solution for production use.

**Comment by lipanpanpanpanpan** [comment]
Thank you very much

**Comment by lipanpanpanpanpan** [comment]
inp = open("D:/PycharmProjects//fm-index-master//fm-index-master//test_data")

        # read input
        data = inp.read()

        # create index
        idx = fmindex.index(data)

        # save index to file
        fmindex.save("data.idx", idx)
when I use it,it shows:
TypeError: write() argument must be str, not bytes

**Comment by lipanpanpanpanpan** [comment]
inp = open("D:/PycharmProjects//fm-index-master//fm-index-master//test_data")
 # read input
 data = inp.read()
 # create index
 idx = fmindex.index(data)
 # save index to file
 fmindex.save("data.idx", idx)
when I use it,it shows:
TypeError: write() argument must be str, not bytes

**Comment by lipanpanpanpanpan** [comment]
inp = open("D:/PycharmProjects//fm-index-master//fm-index-master//test_data")
 data = inp.read()
 idx = fmindex.index(data)
 fmindex.save("data.idx", idx)
when I use it,it shows:TypeError: write() argument must be str, not bytes

**Comment by lipanpanpanpanpan** [comment]
inp = open("D:/PycharmProjects//fm-index-master//fm-index-master//test_data")
 data = inp.read()
 idx = fmindex.index(data)
 fmindex.save("data.idx", idx)
when I use it,it shows:TypeError: write() argument must be str, not bytes


在 2018-09-28 15:34:48，"Egon Elbre" <notifications@github.com> 写道：


Closed #1.

**Comment by egonelbre** [comment]
You can try the latest version. It was a Python 3 incompatibility with Python 2.

**Comment by lipanpanpanpanpan** [comment]
OK,thank you.





At 2018-09-29 01:30:51, "Egon Elbre" <notifications@github.com> wrote:


You can try the latest version. It was a Python 3 incompatibility with Python 2.
